language: node_js
node_js:
  - "10.15.1"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE numerology-test;" -U postgres
  - psql -c "CREATE USER matrayu WITH PASSWORD 'bar';" -U postgres